spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        newBookInput-in-0:
            content-type: application/json
            destination: NEW_BOOK_EVENT

    function:
      definition: newBookInput
